# https://ci.appveyor.com/project/goanpeca/qtpy

branches:
  only:
    - master

matrix:
  fast_finish: true

environment:
  global:
      PYTHON: "C:\\conda"
      CMD_IN_ENV: "cmd /E:ON /V:ON /C .\\ci-helpers\\appveyor\\windows_sdk.cmd"
      PYTHON_ARCH: "64" # needs to be set for CMD_IN_ENV to succeed. If a mix
                        # of 32 bit and 64 bit builds are needed, move this
                        # to the matrix section.
  matrix:
    # PyQt5
    - PYTHON_VERSION: "3.4"
      CONDA_DEPENDENCIES: "qt=5.* pyqt=5.*"
    - PYTHON_VERSION: "2.7"
      CONDA_DEPENDENCIES: "qt=5.* pyqt=5.*"
    # PyQt4
    - PYTHON_VERSION: "3.4"
      CONDA_DEPENDENCIES: "qt=4.* pyqt=4.*"
    - PYTHON_VERSION: "2.7"
      CONDA_DEPENDENCIES: "qt=4.* pyqt=4.*"
    # PySide
#    - PYTHON_VERSION: "2.7"
#      CONDA_DEPENDENCIES: "qt=4.* pyside"

platform:
    -x64

install:
    # If there is a newer build queued for the same PR, cancel this one.
    # The AppVeyor 'rollout builds' option is supposed to serve the same
    # purpose but it is problematic because it tends to cancel builds pushed
    # directly to master instead of just PR builds (or the converse).
    # credits: JuliaLang developers.
    - ps: if ($env:APPVEYOR_PULL_REQUEST_NUMBER -and $env:APPVEYOR_BUILD_NUMBER -ne ((Invoke-RestMethod `
        https://ci.appveyor.com/api/projects/$env:APPVEYOR_ACCOUNT_NAME/$env:APPVEYOR_PROJECT_SLUG/history?recordsNumber=50).builds | `
        Where-Object pullRequestId -eq $env:APPVEYOR_PULL_REQUEST_NUMBER)[0].buildNumber) { `
          throw "There are newer queued builds for this pull request, failing early." }
    - "git clone git://github.com/astropy/ci-helpers.git"
    - "powershell ci-helpers/appveyor/install-miniconda.ps1"
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - "activate test"
    - "conda install ciocheck -c conda-forge"
    - "python setup.py develop"

# Not a .NET project, we build in the install step instead
build: false

test_script:
  - "%CMD_IN_ENV% python example.py"
  - "%CMD_IN_ENV% py.test qtawesome"
