version: 2

main: &main
    machine: true
    steps:
      - checkout
      - run:
          command: docker pull dorowu/ubuntu-desktop-lxde-vnc:trusty
      - run:
          name: Install system packages
          command: |
            sudo apt-get update
            sudo apt-get install libegl1-mesa
      - run:
          command: ./.circleci/install.sh
      - run:
          command: ./.circleci/run_tests.sh

jobs:
  python2.7:
    <<: *main
    environment:
      - PYTHON_VERSION: "2.7"

  python3.5:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.5"

  python3.6:
    <<: *main
    environment:
      - PYTHON_VERSION: "3.6"

workflows:
  version: 2
  build_and_test:
    jobs:
      - python2.7
      - python3.5
      - python3.6
